### ISSUE TITLE
Увеличить допустимые объём файла

### ISSUE THREAD

**Issue by EgorMaster** [Kylmakalle/Telescopy#5]
Здравствуйте Хочу попросить вас увеличить объём на Боте в телеграмме поскольку 8 Мб - это вообще мало из-за этого приходится делать видео в плохом качестве чтобы загрузить его через бота повысьте хотя бы чтобы был допустимый объём хотя бы 40 - 50 мб Примерно охота действительно загружать через вашего Бота достойные файлы надеюсь на ваше понимание

**Comment by Kylmakalle** [comment]
https://telegra.ph/Telescopy-FAQ-Ru-05-21-3
<img width="658" alt="Telescopy_FAQ_Ru_🇷🇺_–_Telegraph" src="https://user-images.githubusercontent.com/24507532/174449049-56cb19a9-b365-4cfb-b576-9f7bb009a85d.png">
